package com.example.homework3

val listCountry = listOf(
    CountryModel(1, "США", R.drawable.img),
    CountryModel(2, "Китай", R.drawable.img_1),
    CountryModel(3, "Япония", R.drawable.img_2),
    CountryModel(4, "Германия", R.drawable.img_3),
    CountryModel(5, "Индия", R.drawable.img_4),
    CountryModel(6, "Великобритания", R.drawable.img_5),
    CountryModel(7, "Франция", R.drawable.img_6),
    CountryModel(8, "Италия", R.drawable.img_7),
    CountryModel(9, "Бразилия", R.drawable.img_8),
    CountryModel(10, "Канада", R.drawable.img_9),
    CountryModel(11, "Россия", R.drawable.img_10),
    CountryModel(12, "Республика Корея", R.drawable.img_11),
    CountryModel(13, "Испания", R.drawable.img_12),
    CountryModel(14, "Австралия", R.drawable.img_13),
    CountryModel(15, "Мексика", R.drawable.img_14),
    CountryModel(16, "Индонезия", R.drawable.img_15),
    CountryModel(17, "Нидерланды", R.drawable.img_16),
    CountryModel(18, "Саудовская Аравия", R.drawable.img_17),
    CountryModel(19, "Турция", R.drawable.img_18),
    CountryModel(20, "Швейцария", R.drawable.img_19),
    CountryModel(21, "Тайвань", R.drawable.img_20),
    CountryModel(22, "Польша", R.drawable.img_21),
    CountryModel(23, "Иран", R.drawable.img_22),
    CountryModel(24, "Таиланд", R.drawable.img_23),
    CountryModel(25, "Швеция", R.drawable.img_24),
    CountryModel(26, "Бельгия", R.drawable.img_25),
    CountryModel(27, "Нигерия", R.drawable.img_26),
    CountryModel(28, "Австрия", R.drawable.img_27),
    CountryModel(29, "Аргентина", R.drawable.img_28),
    CountryModel(30, "ОАЭ", R.drawable.img_29),
)